version: "3.3"
services:
  service:
    build:
      context: service
    volumes:
      - ./service:/var/www/html
    restart: always
    depends_on:
      - rabbitmq
      - db
  rabbitmq:
    build:
      context: rabbitmq
    ports:
      - "15672:15672"
  db:
    build:
      context: postgres
    environment:
      POSTGRES_PASSWORD: password
